#instaling multiple packages by using loops
- name: install packages
  hosts: mongodb
  become: yes
  tasks: 
  - name: install packages
    ansible.bulitin.yum:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - postmap
    - mailx
